// filepath: /c:/codeingprojects/JavaScript,HTML,CSS/Chessing/request.rest
POST http://localhost:8000/lobby
Content-Type: application/json

{
  "game": {
    "id": 1,
    "name": "Work",
    "players": ["E"]
  }
}